import { core } from '@card-engine-nx/cards';
import { PlayerDeck } from '@card-engine-nx/state';

export const coreSpirit: PlayerDeck = {
  name: 'Core (Spirit)',
  heroes: [core.hero.eowyn, core.hero.eleanor, core.hero.dunhere],
  library: [
    core.ally.wanderingTook,
    core.ally.wanderingTook,
    core.ally.lorienGuide,
    core.ally.lorienGuide,
    core.ally.lorienGuide,
    core.ally.northernTracker,
    core.ally.northernTracker,
    core.event.theGaladhrimsGreeting,
    core.event.theGaladhrimsGreeting,
    core.event.strengthOfWill,
    core.event.strengthOfWill,
    core.event.hastyStroke,
    core.event.hastyStroke,
    core.event.willOfTheWest,
    core.event.willOfTheWest,
    core.event.aTestOfWill,
    core.event.aTestOfWill,
    core.event.standAndFight,
    core.event.standAndFight,
    core.event.standAndFight,
    core.event.aLightInIheDark,
    core.event.aLightInIheDark,
    core.event.dwarvenTomb,
    core.event.fortuneOrFate,
    core.attachment.theFavorOfTheLady,
    core.attachment.theFavorOfTheLady,
    core.attachment.powerInTheEarth,
    core.attachment.powerInTheEarth,
    core.attachment.unexpectedCourage,
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.gandalf,
  ],
};
