import { core } from '@card-engine-nx/cards';
import { PlayerDeck } from '@card-engine-nx/state';

export const coreLeadershipSpirit: PlayerDeck = {
  name: 'Core (Leadership & Spirit)',
  heroes: [core.hero.aragorn, core.hero.theodred, core.hero.eowyn],
  library: [
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.faramir,
    core.ally.faramir,
    core.ally.guardOfTheCitadel,
    core.ally.guardOfTheCitadel,
    core.ally.guardOfTheCitadel,
    core.ally.longbeardOrcSlayer,
    core.ally.longbeardOrcSlayer,
    core.ally.silverlodeArcher,
    core.ally.silverlodeArcher,
    core.ally.snowbournScout,
    core.ally.snowbournScout,
    core.ally.snowbournScout,
    core.ally.sonOfArnor,
    core.ally.sonOfArnor,
    core.ally.lorienGuide,
    core.ally.lorienGuide,
    core.ally.northernTracker,
    core.ally.northernTracker,
    core.ally.wanderingTook,
    core.ally.wanderingTook,
    core.ally.wanderingTook,
    core.event.grimResolve,
    core.event.grimResolve,
    core.event.sneakAttack,
    core.event.sneakAttack,
    core.event.sneakAttack,
    core.event.valiantSacrifice,
    core.event.valiantSacrifice,
    core.event.valiantSacrifice,
    core.event.aTestOfWill,
    core.event.aTestOfWill,
    core.event.aTestOfWill,
    core.event.dwarvenTomb,
    core.event.dwarvenTomb,
    core.event.standAndFight,
    core.event.standAndFight,
    core.event.theGaladhrimsGreeting,
    core.event.theGaladhrimsGreeting,
    core.attachment.celebriansStone,
    core.attachment.celebriansStone,
    core.attachment.celebriansStone,
    core.attachment.stewardOfGondor,
    core.attachment.stewardOfGondor,
    core.attachment.stewardOfGondor,
    core.attachment.unexpectedCourage,
    core.attachment.unexpectedCourage,
    core.attachment.unexpectedCourage,
  ],
};
