import { core } from '@card-engine-nx/cards';
import { PlayerDeck } from '@card-engine-nx/state';

export const coreLeadership: PlayerDeck = {
  name: 'Core (Tactics)',
  heroes: [core.hero.aragorn, core.hero.theodred, core.hero.gloin],
  library: [
    core.ally.guardOfTheCitadel,
    core.ally.guardOfTheCitadel,
    core.ally.guardOfTheCitadel,
    core.ally.faramir,
    core.ally.faramir,
    core.ally.sonOfArnor,
    core.ally.sonOfArnor,
    core.ally.snowbournScout,
    core.ally.snowbournScout,
    core.ally.snowbournScout,
    core.ally.silverlodeArcher,
    core.ally.silverlodeArcher,
    core.ally.longbeardOrcSlayer,
    core.ally.longbeardOrcSlayer,
    core.ally.brokIronfist,
    core.event.everVigilant,
    core.event.everVigilant,
    core.event.commonCause,
    core.event.commonCause,
    core.event.forGondor,
    core.event.forGondor,
    core.event.sneakAttack,
    core.event.sneakAttack,
    core.event.valiantSacrifice,
    core.event.valiantSacrifice,
    core.event.grimResolve,
    core.attachment.stowardOfGondor,
    core.attachment.stowardOfGondor,
    core.attachment.celebriansStore,
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.gandalf,
  ],
};
