import { core } from '@card-engine-nx/cards';
import { PlayerDeck } from '@card-engine-nx/state';

export const coreLoreTactics: PlayerDeck = {
  name: 'Core (Lore & Tactics)',
  heroes: [core.hero.beravor, core.hero.denethor, core.hero.legolas],
  library: [
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.gleowine,
    core.ally.gleowine,
    core.ally.gleowine,
    core.ally.henamarthRiversong,
    core.ally.henamarthRiversong,
    core.ally.henamarthRiversong,
    core.ally.daughterOfTheNimrodel,
    core.ally.daughterOfTheNimrodel,
    core.ally.daughterOfTheNimrodel,
    core.ally.ereborHammersmith,
    core.ally.ereborHammersmith,
    core.ally.ereborHammersmith,
    core.ally.minerOfTheIronHills,
    core.ally.minerOfTheIronHills,
    core.ally.minerOfTheIronHills,
    core.ally.gondorianSpearman,
    core.ally.gondorianSpearman,
    core.ally.gondorianSpearman,
    core.ally.veteranAxehand,
    core.ally.veteranAxehand,
    core.ally.veteranAxehand,
    core.event.radagastsCunning,
    core.event.radagastsCunning,
    core.event.radagastsCunning,
    core.event.secretPaths,
    core.event.secretPaths,
    core.event.secretPaths,
    core.event.bladeMastery,
    core.event.bladeMastery,
    core.event.bladeMastery,
    core.event.feint,
    core.event.feint,
    core.event.feint,
    core.event.quickStrike,
    core.event.quickStrike,
    core.event.quickStrike,
    core.attachment.forestSnare,
    core.attachment.forestSnare,
    core.attachment.protectorOfLorien,
    core.attachment.protectorOfLorien,
    core.attachment.protectorOfLorien,
    core.attachment.hornOfGondor,
    core.attachment.hornOfGondor,
    core.attachment.hornOfGondor,
    core.attachment.bladeOfGondolin,
    core.attachment.bladeOfGondolin,
    core.attachment.bladeOfGondolin,
  ],
};
