import { core } from '@card-engine-nx/cards';
import { PlayerDeck } from '@card-engine-nx/state';

export const coreLore: PlayerDeck = {
  name: 'Core (Tactics)',
  heroes: [core.hero.denethor, core.hero.glorfindel, core.hero.beravor],
  library: [
    core.ally.daughterOfTheNimrodel,
    core.ally.daughterOfTheNimrodel,
    core.ally.daughterOfTheNimrodel,
    core.ally.ereborHammersmith,
    core.ally.ereborHammersmith,
    core.ally.henamarthRiversong,
    core.ally.minerOfTheIronHills,
    core.ally.minerOfTheIronHills,
    core.ally.gleowine,
    core.ally.gleowine,
    core.event.loreOfImladris,
    core.event.loreOfImladris,
    core.event.loreOfImladris,
    core.event.loriensWealth,
    core.event.loriensWealth,
    core.event.radagastsCunning,
    core.event.radagastsCunning,
    core.event.secretPaths,
    core.event.secretPaths,
    core.event.gandalfsSearch,
    core.event.gandalfsSearch,
    core.event.beornsHospitality,
    core.attachment.forestSnare,
    core.attachment.forestSnare,
    core.attachment.protectorOfLorien,
    core.attachment.protectorOfLorien,
    core.attachment.darkKnowledge,
    core.attachment.selfPreservation,
    core.attachment.selfPreservation,
    core.ally.gandalf,
    core.ally.gandalf,
    core.ally.gandalf,
  ],
};
