import * as ally from '../allies';
import * as attachment from '../attachments';
import * as event from '../events';
import * as hero from '../heroes';
import { PlayerDeck } from '@card-engine-nx/state';

export const coreLeadershipSpirit: PlayerDeck = {
  name: 'Core (Leadership & Spirit)',
  heroes: [hero.aragorn, hero.theodred, hero.eowyn],
  library: [
    ally.gandalf,
    ally.gandalf,
    ally.gandalf,
    ally.faramir,
    ally.faramir,
    ally.guardOfTheCitadel,
    ally.guardOfTheCitadel,
    ally.guardOfTheCitadel,
    ally.longbeardOrcSlayer,
    ally.longbeardOrcSlayer,
    ally.silverlodeArcher,
    ally.silverlodeArcher,
    ally.snowbournScout,
    ally.snowbournScout,
    ally.snowbournScout,
    ally.sonOfArnor,
    ally.sonOfArnor,
    ally.lorienGuide,
    ally.lorienGuide,
    ally.northernTracker,
    ally.northernTracker,
    ally.wanderingTook,
    ally.wanderingTook,
    ally.wanderingTook,
    event.grimResolve,
    event.grimResolve,
    event.sneakAttack,
    event.sneakAttack,
    event.sneakAttack,
    event.valiantSacrifice,
    event.valiantSacrifice,
    event.valiantSacrifice,
    event.aTestOfWill,
    event.aTestOfWill,
    event.aTestOfWill,
    event.dwarvenTomb,
    event.dwarvenTomb,
    event.standAndFight,
    event.standAndFight,
    event.theGaladhrimsGreeting,
    event.theGaladhrimsGreeting,
    attachment.celebriansStone,
    attachment.celebriansStone,
    attachment.celebriansStone,
    attachment.stewardOfGondor,
    attachment.stewardOfGondor,
    attachment.stewardOfGondor,
    attachment.unexpectedCourage,
    attachment.unexpectedCourage,
    attachment.unexpectedCourage,
  ],
};
